### ISSUE TITLE
截取角色Wiki页面出错

### ISSUE THREAD

**Issue by ouhuangoaa** [lgc-NB2Dev/nonebot-plugin-bawiki#38]
08-04 11:22:49 [ERROR] nonebot_plugin_bawiki | 截取wiki页面出错 https://ba.gamekee.com/581679.html
Traceback (most recent call last):
  File "<string>", line 15, in <module>
  File "C:\Users\Administrator\Desktop\nb\arona\.venv\lib\site-packages\nonebot\__init__.py", line 333, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\nb\arona\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 199, in run
    uvicorn.run(
  File "C:\Users\Administrator\Desktop\nb\arona\.venv\lib\site-packages\uvicorn\main.py", line 587, in run
    server.run()
  File "C:\Users\Administrator\Desktop\nb\arona\.venv\lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\Desktop\nb\arona\.venv\lib\site-packages\nonebot\message.py", line 467, in check_and_run_matcher
    await _run_matcher(
  File "C:\Users\Administrator\Desktop\nb\arona\.venv\lib\site-packages\nonebot\message.py", line 419, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\Desktop\nb\arona\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 759, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\Desktop\nb\arona\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 734, in simple_run
    await handler(
  File "C:\Users\Administrator\Desktop\nb\arona\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\Administrator\Desktop\nb\arona\.venv\lib\site-packages\nonebot_plugin_bawiki\command\stu_wiki_gamekee.py", line 53, in _
    await send_wiki_page(sid, matcher)
> File "C:\Users\Administrator\Desktop\nb\arona\.venv\lib\site-packages\nonebot_plugin_bawiki\data\gamekee.py", line 110, in send_wiki_page
    img = await game_kee_get_page(url)
  File "C:\Users\Administrator\Desktop\nb\arona\.venv\lib\site-packages\nonebot_plugin_bawiki\data\gamekee.py", line 97, in game_kee_get_page
    await page.eval_on_selector(".wiki-footer", js_str)
  File "C:\Users\Administrator\Desktop\nb\arona\.venv\lib\site-packages\playwright\async_api\_generated.py", line 8786, in eval_on_selector
    await self._impl_obj.eval_on_selector(
  File "C:\Users\Administrator\Desktop\nb\arona\.venv\lib\site-packages\playwright\_impl\_page.py", line 409, in eval_on_selector
    return await self._main_frame.eval_on_selector(
  File "C:\Users\Administrator\Desktop\nb\arona\.venv\lib\site-packages\playwright\_impl\_frame.py", line 384, in eval_on_selector
    await self._channel.send(
  File "C:\Users\Administrator\Desktop\nb\arona\.venv\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Users\Administrator\Desktop\nb\arona\.venv\lib\site-packages\playwright\_impl\_connection.py", line 482, in wrap_api_call
    return await cb()
  File "C:\Users\Administrator\Desktop\nb\arona\.venv\lib\site-packages\playwright\_impl\_connection.py", line 97, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Error: failed to find element matching selector ".wiki-footer"

**Comment by lgc2333** [comment]
应该是网页结构有变动
