### ISSUE TITLE
功能经常报错有时又能用

### ISSUE THREAD

**Issue by Rod-fish** [lgc-NB2Dev/nonebot-plugin-bawiki#45]
```
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-XNwg48JX-py3.9/lib/python3.9/site-packages/anyio/_core/_sockets.py", line 164, in try_connect
    stream = await asynclib.connect_tcp(remote_host, remote_port, local_address)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-XNwg48JX-py3.9/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 1691, in connect_tcp
    await get_running_loop().create_connection(
  File "uvloop/loop.pyx", line 2039, in create_connection
    raise exceptions[0]
  File "uvloop/loop.pyx", line 2016, in uvloop.loop.Loop.create_connection
    await waiter
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-XNwg48JX-py3.9/lib/python3.9/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-XNwg48JX-py3.9/lib/python3.9/site-packages/httpcore/backends/asyncio.py", line 111, in connect_tcp
    stream: anyio.abc.ByteStream = await anyio.connect_tcp(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-XNwg48JX-py3.9/lib/python3.9/site-packages/anyio/_core/_sockets.py", line 222, in connect_tcp
    raise OSError("All connection attempts failed") from cause
OSError: All connection attempts failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-XNwg48JX-py3.9/lib/python3.9/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-XNwg48JX-py3.9/lib/python3.9/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-XNwg48JX-py3.9/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 253, in handle_async_request
    raise exc
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-XNwg48JX-py3.9/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-XNwg48JX-py3.9/lib/python3.9/site-packages/httpcore/_async/http_proxy.py", line 261, in handle_async_request
    connect_response = await self._connection.handle_async_request(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-XNwg48JX-py3.9/lib/python3.9/site-packages/httpcore/_async/connection.py", line 86, in handle_async_request
    raise exc
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-XNwg48JX-py3.9/lib/python3.9/site-packages/httpcore/_async/connection.py", line 63, in handle_async_request
    stream = await self._connect(request)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-XNwg48JX-py3.9/lib/python3.9/site-packages/httpcore/_async/connection.py", line 111, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-XNwg48JX-py3.9/lib/python3.9/site-packages/httpcore/backends/auto.py", line 29, in connect_tcp
    return await self._backend.connect_tcp(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-XNwg48JX-py3.9/lib/python3.9/site-packages/httpcore/backends/asyncio.py", line 111, in connect_tcp
    stream: anyio.abc.ByteStream = await anyio.connect_tcp(
  File "/usr/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-XNwg48JX-py3.9/lib/python3.9/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc)
httpcore.ConnectError: All connection attempts failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/my/bot/zhenxun_bot/bot.py", line 22, in <module>
    nonebot.run()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-XNwg48JX-py3.9/lib/python3.9/site-packages/nonebot/__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-XNwg48JX-py3.9/lib/python3.9/site-packages/nonebot/drivers/fastapi.py", line 172, in run
    uvicorn.run(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-XNwg48JX-py3.9/lib/python3.9/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-XNwg48JX-py3.9/lib/python3.9/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-XNwg48JX-py3.9/lib/python3.9/site-packages/nonebot/message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-XNwg48JX-py3.9/lib/python3.9/site-packages/nonebot/message.py", line 188, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-XNwg48JX-py3.9/lib/python3.9/site-packages/nonebot/internal/matcher/matcher.py", line 727, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-XNwg48JX-py3.9/lib/python3.9/site-packages/nonebot/internal/matcher/matcher.py", line 702, in simple_run
    await handler(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-XNwg48JX-py3.9/lib/python3.9/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/home/my/bot/zhenxun_bot/extensive_plugin/nonebot_plugin_bawiki/command/global_future.py", line 56, in _
    await matcher.finish(await db_global_future(all_img=True))
  File "/home/my/bot/zhenxun_bot/extensive_plugin/nonebot_plugin_bawiki/data/bawiki.py", line 163, in db_global_future
    data = (await db_get_wiki_data())["global_future"]
  File "/home/my/bot/zhenxun_bot/extensive_plugin/nonebot_plugin_bawiki/data/bawiki.py", line 28, in db_get_wiki_data
    return await db_get("data/wiki.json")
  File "/home/my/bot/zhenxun_bot/extensive_plugin/nonebot_plugin_bawiki/data/bawiki.py", line 24, in db_get
    return await async_req(f"{config.ba_bawiki_db_url}{suffix}", raw=raw)  # type: ignore
  File "/home/my/bot/zhenxun_bot/extensive_plugin/nonebot_plugin_bawiki/util.py", line 131, in async_req
    resp = await cli.request(method, url, params=params, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-XNwg48JX-py3.9/lib/python3.9/site-packages/httpx/_client.py", line 1533, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-XNwg48JX-py3.9/lib/python3.9/site-packages/httpx/_client.py", line 1620, in send
    response = await self._send_handling_auth(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-XNwg48JX-py3.9/lib/python3.9/site-packages/httpx/_client.py", line 1648, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-XNwg48JX-py3.9/lib/python3.9/site-packages/httpx/_client.py", line 1685, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-XNwg48JX-py3.9/lib/python3.9/site-packages/httpx/_client.py", line 1722, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-XNwg48JX-py3.9/lib/python3.9/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/usr/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-XNwg48JX-py3.9/lib/python3.9/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: All connection attempts failed
```

在使用千里眼和查漫画等功能经常出现这样的报错，我想问一下这里是网络问题导致还是什么

**Comment by lgc2333** [comment]
可能是CDN使用的 域名SSL证书 / 域名本身 到期了，建议参考 [文档](https://github.com/lgc-NB2Dev/nonebot-plugin-bawiki#%EF%B8%8F-%E9%85%8D%E7%BD%AE) 挂上代理并换源使用
