### ISSUE TITLE
[Bug] ba总力战 返回 获取图片失败，请检查后台输出

### ISSUE THREAD

**Issue by sgpublic** [lgc-NB2Dev/nonebot-plugin-bawiki#48]
rt

```
nonebot-arona  | 10-13 11:39:13 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_bawiki.command.raid) running complete
nonebot-arona  | 10-13 11:39:22 [SUCCESS] nonebot | OneBot V11 3598402309 | [message.group.normal]: Message 1806236031 from 3300633844@[群:301811702] 'ba总力战 -s c'
nonebot-arona  | 10-13 11:39:22 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_bawiki.command.raid)
nonebot-arona  | 10-13 11:39:22 [ERROR] nonebot_plugin_bawiki | 获取总力战wiki失败
nonebot-arona  | Traceback (most recent call last):
nonebot-arona  |   File "<string>", line 15, in <module>
nonebot-arona  |   File "/home/poetry-runner/.cache/pypoetry/virtualenvs/arona-9TtSrW0h-py3.11/lib/python3.11/site-packages/nonebot/__init__.py", line 333, in run
nonebot-arona  |     get_driver().run(*args, **kwargs)
nonebot-arona  |   File "/home/poetry-runner/.cache/pypoetry/virtualenvs/arona-9TtSrW0h-py3.11/lib/python3.11/site-packages/nonebot/drivers/fastapi.py", line 199, in run
nonebot-arona  |     uvicorn.run(
nonebot-arona  |   File "/home/poetry-runner/.cache/pypoetry/virtualenvs/arona-9TtSrW0h-py3.11/lib/python3.11/site-packages/uvicorn/main.py", line 587, in run
nonebot-arona  |     server.run()
nonebot-arona  |   File "/home/poetry-runner/.cache/pypoetry/virtualenvs/arona-9TtSrW0h-py3.11/lib/python3.11/site-packages/uvicorn/server.py", line 61, in run
nonebot-arona  |     return asyncio.run(self.serve(sockets=sockets))
nonebot-arona  |   File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
nonebot-arona  |     return runner.run(main)
nonebot-arona  |   File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
nonebot-arona  |     return self._loop.run_until_complete(task)
nonebot-arona  |   File "/home/poetry-runner/.cache/pypoetry/virtualenvs/arona-9TtSrW0h-py3.11/lib/python3.11/site-packages/nonebot/message.py", line 467, in check_and_run_matcher
nonebot-arona  |     await _run_matcher(
nonebot-arona  |   File "/home/poetry-runner/.cache/pypoetry/virtualenvs/arona-9TtSrW0h-py3.11/lib/python3.11/site-packages/nonebot/message.py", line 419, in _run_matcher
nonebot-arona  |     await matcher.run(bot, event, state, stack, dependency_cache)
nonebot-arona  |   File "/home/poetry-runner/.cache/pypoetry/virtualenvs/arona-9TtSrW0h-py3.11/lib/python3.11/site-packages/nonebot/internal/matcher/matcher.py", line 759, in run
nonebot-arona  |     await self.simple_run(bot, event, state, stack, dependency_cache)
nonebot-arona  |   File "/home/poetry-runner/.cache/pypoetry/virtualenvs/arona-9TtSrW0h-py3.11/lib/python3.11/site-packages/nonebot/internal/matcher/matcher.py", line 734, in simple_run
nonebot-arona  |     await handler(
nonebot-arona  |   File "/home/poetry-runner/.cache/pypoetry/virtualenvs/arona-9TtSrW0h-py3.11/lib/python3.11/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__
nonebot-arona  |     return await cast(Callable[..., Awaitable[R]], self.call)(**values)
nonebot-arona  | > File "/home/poetry-runner/.cache/pypoetry/virtualenvs/arona-9TtSrW0h-py3.11/lib/python3.11/site-packages/nonebot_plugin_bawiki/command/raid.py", line 127, in _
nonebot-arona  |     ret = await asyncio.gather(*tasks)
nonebot-arona  |   File "/home/poetry-runner/.cache/pypoetry/virtualenvs/arona-9TtSrW0h-py3.11/lib/python3.11/site-packages/nonebot_plugin_bawiki/data/bawiki.py", line 116, in db_wiki_raid
nonebot-arona  |     img.append(i[s])
nonebot-arona  | IndexError: list index out of range
```

配置如下：

```
BA_BAWIKI_DB_URL=https://gitee.com/sgpublic/bawiki-data/raw/main/
```

**Comment by lgc2333** [comment]
数据源问题，欢迎向数据源贡献数据
