### ISSUE TITLE
加载失败

### ISSUE THREAD

**Issue by RainbowDashKira** [lgc-NB2Dev/nonebot-plugin-bawiki#59]
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "E:\BOT\rainbow\.venv\lib\site-packages\nonebot\plugin\load.py", line 131, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "E:\BOT\rainbow\.venv\lib\site-packages\nonebot\plugin\load.py", line 65, in load_all_plugins
    return manager.load_all_plugins()
  File "E:\BOT\rainbow\.venv\lib\site-packages\nonebot\plugin\manager.py", line 203, in load_all_plugins
    return set(
  File "E:\BOT\rainbow\.venv\lib\site-packages\nonebot\plugin\manager.py", line 204, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "E:\BOT\rainbow\.venv\lib\site-packages\nonebot\plugin\manager.py", line 167, in load_plugin
    module = importlib.import_module(self._third_party_plugin_ids[name])
  File "C:\Users\10905\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "E:\BOT\rainbow\.venv\lib\site-packages\nonebot\plugin\manager.py", line 255, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\BOT\rainbow\.venv\lib\site-packages\nonebot_plugin_bawiki\__init__.py", line 27, in <module>
    load_commands()
  File "E:\BOT\rainbow\.venv\lib\site-packages\nonebot_plugin_bawiki\command\__init__.py", line 36, in load_commands
    module = importlib.import_module(f".{module.stem}", __package__)
  File "C:\Users\10905\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\BOT\rainbow\.venv\lib\site-packages\nonebot_plugin_bawiki\command\logo_generate.py", line 10, in <module>
    from ..data.logo_generate import get_logo
  File "E:\BOT\rainbow\.venv\lib\site-packages\nonebot_plugin_bawiki\data\logo_generate.py", line 2, in <module>
    from .playwright import get_routed_page
  File "E:\BOT\rainbow\.venv\lib\site-packages\nonebot_plugin_bawiki\data\playwright.py", line 20, in <module>
    from pil_utils.fonts import Font, get_proper_font
ModuleNotFoundError: No module named 'pil_utils.fonts'

**Comment by lgc2333** [comment]
降级pil-utils

```shell
pip install "pil-utils<0.2"
```

可能和其他插件（比如memes）不兼容，但是修复无限期延迟

**Comment by RainbowDashKira** [comment]
好的 谢谢.
